In [1]:
import os
from sklearn import datasets
import sklearn.datasets
import sklearn.ensemble
import numpy as np


In [2]:
iris = sklearn.datasets.load_iris()

In [3]:
X=iris.data
Y=iris.target

In [4]:
X.shape

(150, 4)

In [5]:
Y.shape

(150,)

In [6]:
from sklearn.preprocessing import MinMaxScaler
minmax_scaler = MinMaxScaler(feature_range=(0, 1))
minmax_scaler.fit(X)

MinMaxScaler()

In [7]:
X=minmax_scaler.transform(X)

In [8]:
X

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [9]:
train, test, labels_train, labels_test = sklearn.model_selection.train_test_split(X, Y, train_size=0.90)

In [10]:
train.shape

(135, 4)

In [11]:
test.shape

(15, 4)

In [12]:
labels_train

array([1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 0, 1, 1, 1, 2, 2, 1, 1, 2,
       2, 1, 0, 2, 0, 0, 1, 0, 0, 1, 2, 2, 2, 1, 2, 0, 0, 2, 1, 0, 0, 2,
       2, 1, 1, 1, 0, 1, 2, 2, 0, 1, 0, 0, 1, 2, 0, 0, 1, 1, 0, 2, 0, 2,
       2, 1, 0, 2, 1, 1, 1, 2, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 1, 0, 1, 0,
       1, 2, 2, 0, 1, 1, 0, 1, 0, 2, 0, 0, 1, 2, 0, 1, 1, 1, 0, 0, 0, 2,
       2, 0, 1, 1, 2, 0, 2, 0, 0, 2, 1, 0, 0, 2, 1, 2, 1, 2, 2, 0, 2, 1,
       2, 0, 0])

In [13]:
D = np.c_[train,labels_train]

In [14]:
np.savetxt('iris_train.csv', D, delimiter=",")

In [18]:
import os
import pickle


In [21]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import linear_model
import pandas as pd

chunksize = 25
acc_score_list = []
max_acc_score = 0
for chunk in pd.read_csv('iris_train.csv', header=None, chunksize=chunksize):
    train_sub = chunk
    #print(train_sub)
    Y=train_sub[4]
    X=train_sub.drop([4], axis=1)
    clf = linear_model.SGDClassifier()
    clf.partial_fit(X,Y, classes=np.unique(Y))
    print(clf.coef_)
    clf.predict(test)
    pred=clf.predict(test)
    curr_acc_score = accuracy_score(pred, labels_test)
    acc_score_list.append(curr_acc_score)
    if (max(acc_score_list)== curr_acc_score ):
        filename = 'iris_updatable_clasifier.pras'
        pickle.dump(clf, open(filename, 'wb'))
    print(pred)
    print(curr_acc_score)
    

[[ -7.05295139  10.17252604 -14.06912076 -15.05533854]
 [ -7.05295139  -0.40690104  -5.79316737  -6.91731771]
 [ -5.15407986 -11.80013021  -0.82759534   6.10351562]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]
0.2
[[ -8.40928819   9.765625   -14.8967161  -14.6484375 ]
 [  1.08506944  -6.51041667   4.13797669   3.66210938]
 [ 13.83463542  -9.35872396  19.20021186  19.93815104]]
[2. 2. 2. 2. 2. 0. 0. 2. 2. 2. 2. 2. 2. 2. 0.]
0.6666666666666666
[[-7.59548611e+00  1.05794271e+01 -1.58898305e+01 -1.34277344e+01]
 [ 5.69661458e+00 -4.06901042e+00  5.95868644e+00 -6.06546063e-15]
 [ 8.68055556e+00 -4.88281250e+00  1.22484110e+01  1.66829427e+01]]
[1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0.]
0.5333333333333333
[[ 8.13802083e-01  4.88281250e+00 -2.64830508e+00 -3.25520833e+00]
 [-5.42534722e-01 -8.13802083e+00 -4.30349576e+00 -1.26139323e+01]
 [ 7.59548611e+00 -4.76571907e-15  1.47311970e+01  1.95312500e+01]]
[2. 2. 2. 2. 2. 0. 0. 2. 2. 2. 2. 2. 2. 2. 0.]
0.6666666666666666
[[ -7.86675347 